# Population Change

In [87]:
import sys
import openpyxl
import pandas as pd
import seaborn as sns

%matplotlib inline

!python -V
print(sys.executable)

Python 3.9.6
C:\Users\HAL9000\anaconda3\envs\data_science\python.exe

## 1. Import Data

### .xlsx

In [88]:
try:
    pop = openpyxl.load_workbook('bev_meld.xlsx')
except IOError as err:
    print(f'Error: {e}')

sheet = pop['Gemeinden']
sheet

C:\Users\HAL9000\anaconda3\envs\data_science\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

### .csv

In [89]:
# Import data

try: 
    population = pd.read_csv('bev_meld.csv', skiprows=2, encoding='latin1')
except Exception as err:
    print(f'Errortype: {err.__class__.__name__}')
    print(f'Error: {err}')
    raise err
    
population.drop([0,0], inplace=True)

display(population.head())
print('----------------------------------------------------------------------------------------------')
display(population.dtypes.head())
print('----------------------------------------------------------------------------------------------')
print(type(pop))
print('----------------------------------------------------------------------------------------------')
print(population.columns)
print('----------------------------------------------------------------------------------------------')
print(population.info())

,Bezirk,Gemnr,Gemeinde,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,I,70101.0,Innsbruck,111.305,112.174,112.759,109.150,109.763,110.454,110.997,...,119.846,122.458,124.579,126.965,131.009,132.236,132.493,132.110,131.961,131.059
2,IM,70201.0,Arzl im Pitztal,2.492,2.669,2.693,2.737,2.738,2.729,2.779,...,2.989,2.983,3.030,3.039,3.042,3.088,3.134,3.157,3.164,3.140
3,IM,70202.0,Haiming,3.625,3.701,3.677,3.725,3.741,3.739,3.768,...,4.457,4.444,4.474,4.528,4.535,4.608,4.659,4.697,4.757,4.770
4,IM,70203.0,Imst,7.925,8.145,7.984,8.071,8.268,8.399,8.542,...,9.504,9.552,9.661,9.827,10.115,10.371,10.504,10.628,10.765,10.882
5,IM,70204.0,Imsterberg,683.000,687.000,703.000,706.000,709.000,722.000,734.000,...,743.000,761.000,757.000,774.000,763.000,769.000,777.000,801.000,801.000,794.000

----------------------------------------------------------------------------------------------

Bezirk       object
Gemnr       float64
Gemeinde     object
1993        float64
1994        float64
dtype: object

----------------------------------------------------------------------------------------------
<class 'openpyxl.workbook.workbook.Workbook'>
----------------------------------------------------------------------------------------------
Index(['Bezirk', 'Gemnr', 'Gemeinde', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')
----------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 279 entries, 1 to 279
Data columns (total 32 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Bezirk    279 non-null    object
 1   Gemnr     279 non-null    float64
 2   Gemeinde  279 non-null    object
 3   1993      279 non-null    float64
 4   1994      279 non-null    float64
 5   1995      279 non-null    float64
 6   1996      279 non-null    float64
 7   1997      279 non-null    float64
 8   1998      279 non-null    float64
 9   1999      279 non-null    float64
 10  2000      279 non-null    float64
 11  2001      279 non-null    float64
 12  2002      279 non-null    float64
 13  2003      279 non-null    float64
 14  2004      279 non-null    float64
 15  2005      279 non-null    float64
 16  2006      279 non-null    float64
 17  2007      279 non-null    float64
 18  2008      279 non-null    float64
 19  2009      279 non-null    float64
 20  2010      279 non-null    float64
 21  2011      279 non-null    float64
 22  2012      279 non-null    float64
 23  2013      279 non-null    float64
 24  2014      279 non-null    float64
 25  2015      279 non-null    float64
 26  2016      279 non-null    float64
 27  2017      279 non-null    float64
 28  2018      279 non-null    float64
 29  2019      279 non-null    float64
 30  2020      279 non-null    float64
 31  2021      279 non-null    float64
dtypes: float64(30), object(2)
memory usage: 71.9+ KB
None

In [90]:
# Group data
bezirk = population.groupby('Bezirk')
display(bezirk.head(2))
display(bezirk.mean())

,Bezirk,Gemnr,Gemeinde,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,I,70101.0,Innsbruck,111.305,112.174,112.759,109.150,109.763,110.454,110.997,...,119.846,122.458,124.579,126.965,131.009,132.236,132.493,132.110,131.961,131.059
2,IM,70201.0,Arzl im Pitztal,2.492,2.669,2.693,2.737,2.738,2.729,2.779,...,2.989,2.983,3.030,3.039,3.042,3.088,3.134,3.157,3.164,3.140
3,IM,70202.0,Haiming,3.625,3.701,3.677,3.725,3.741,3.739,3.768,...,4.457,4.444,4.474,4.528,4.535,4.608,4.659,4.697,4.757,4.770
26,IL,70301.0,Absam,6.418,6.184,6.206,6.179,6.196,6.219,6.374,...,6.723,6.766,6.756,6.774,6.910,6.990,7.112,7.285,7.311,7.319
27,IL,70302.0,Aldrans,1.823,1.831,1.885,1.884,1.901,1.917,1.929,...,2.212,2.315,2.421,2.500,2.564,2.658,2.684,2.736,2.723,2.761
91,KB,70401.0,Aurach bei KitzbÃ¼hel,1.098,1.131,1.153,1.169,1.201,1.222,1.216,...,1.135,1.119,1.104,1.100,1.092,1.125,1.130,1.130,1.116,1.132
92,KB,70402.0,Brixen im Thale,2.389,2.412,2.463,2.514,2.514,2.535,2.558,...,2.663,2.646,2.619,2.639,2.615,2.627,2.639,2.639,2.639,2.636
111,KU,70501.0,Alpbach,2.295,2.299,2.332,2.339,2.368,2.359,2.349,...,2.584,2.569,2.572,2.580,2.560,2.558,2.561,2.543,2.533,2.538
112,KU,70502.0,Angath,750.000,754.000,756.000,725.000,750.000,759.000,845.000,...,946.000,960.000,985.000,999.000,1.008,1.010,1.008,986.000,1.006,1.031
141,LA,70601.0,Faggen,251.000,269.000,260.000,258.000,263.000,274.000,275.000,...,370.000,372.000,366.000,370.000,373.000,369.000,383.000,378.000,390.000,383.000
142,LA,70602.0,Fendels,212.000,223.000,229.000,225.000,232.000,239.000,247.000,...,267.000,253.000,252.000,253.000,247.000,254.000,259.000,253.000,263.000,275.000
171,LZ,70701.0,Abfaltersbach,642.000,624.000,619.000,626.000,625.000,614.000,624.000,...,652.000,646.000,634.000,647.000,644.000,646.000,630.000,644.000,646.000,647.000
172,LZ,70702.0,Ainet,1.016,1.019,1.019,1.031,1.010,1.011,1.018,...,919.000,920.000,910.000,912.000,906.000,924.000,936.000,933.000,920.000,921.000
204,RE,70801.0,Bach,687.000,738.000,737.000,737.000,720.000,714.000,708.000,...,686.000,669.000,656.000,641.000,630.000,629.000,614.000,612.000,623.000,634.000
205,RE,70802.0,Berwang,575.000,608.000,622.000,622.000,652.000,640.000,636.000,...,584.000,571.000,565.000,564.000,554.000,547.000,565.000,564.000,586.000,597.000
241,SZ,70901.0,Achenkirch,2.127,2.054,2.093,2.111,2.112,2.090,2.084,...,2.149,2.130,2.118,2.105,2.181,2.226,2.185,2.199,2.198,2.169
242,SZ,70902.0,Aschau im Zillertal,1.364,1.378,1.396,1.417,1.457,1.464,1.481,...,1.731,1.725,1.728,1.749,1.821,1.840,1.866,1.845,1.844,1.866

,Gemnr,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Bezirk,,,,,,,,,,,,,,,,,,,,,
I,70101.000000,111.305000,112.174000,112.759000,109.150000,109.763000,110.454000,110.997000,111.752000,112.350000,...,119.846000,122.458000,124.579000,126.965000,131.009000,132.236000,132.493000,132.110000,131.961000,131.059000
IL,70335.246154,224.161062,211.730662,197.470969,184.221615,186.478862,173.180631,173.947908,176.279692,176.601169,...,170.078954,185.877354,172.086969,144.673846,145.936862,131.410462,117.789508,118.719585,118.153015,119.447815
IM,70212.500000,172.239833,175.172833,177.682667,179.330625,180.476708,182.899542,183.875250,184.630542,185.104125,...,110.083792,110.068708,110.444792,111.251625,110.568125,111.390208,152.165250,155.266083,154.534250,154.303167
KB,70410.500000,65.488600,65.539300,65.456150,66.337950,65.972350,67.701550,69.566850,70.983750,72.195350,...,80.363850,80.717350,80.238700,81.500350,83.525800,83.194350,83.803900,83.963200,85.725800,86.950000
KU,70516.300000,87.062100,88.377533,88.596600,88.414567,87.274067,87.589733,90.341433,88.791633,88.582567,...,96.643667,98.341867,99.181400,100.876933,68.284033,68.775833,69.950000,105.054567,75.371133,76.463167
LA,70615.500000,247.097967,284.274000,254.817300,260.900933,260.967667,261.942067,264.344267,263.948000,266.419867,...,270.824700,238.490667,236.994433,270.360600,238.635467,273.068400,241.639167,209.204133,242.837933,275.637100
LZ,70717.515152,371.275000,342.702879,342.495424,403.436667,373.924515,372.557455,401.497788,370.771273,341.832212,...,413.173636,439.230636,405.928182,405.713424,433.477455,433.684909,431.170879,429.019091,427.868273,397.718939
RE,70819.000000,348.741054,355.417108,357.096405,357.103405,331.508000,334.076865,333.216081,334.974865,333.759405,...,325.989514,324.423324,321.697000,320.671514,324.568838,326.009649,327.552243,326.259973,327.911514,328.592351
SZ,70921.435897,215.529308,190.264513,191.046974,193.346026,192.341718,193.812410,194.948846,196.620641,171.920385,...,182.239051,156.375667,158.133641,159.301000,160.375949,161.447513,160.849974,161.324590,162.437744,163.696154

# Telfs

## Version 1

In [91]:
population.head()
df_prepared = population.drop(['Bezirk', 'Gemnr'], axis = 1).set_index('Gemeinde')
#df_prepared = population.drop(['Bezirk', 'Gemnr'], axis = 1)
display(df_prepared)
# df_telfs = df_prepared.loc[df_prepared['Gemeinde'] == 'Telfs'].T
df_telfs = df_prepared.loc['Telfs']
display(df_telfs)


print('-------------------------------------------------------------')
# Make df from series
df_telfs.to_frame().info()
print('-------------------------------------------------------------')
df_telfs.dtypes

,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Gemeinde,,,,,,,,,,,,,,,,,,,,,
Innsbruck,111.305,112.174,112.759,109.150,109.763,110.454,110.997,111.752,112.350,112.882,...,119.846,122.458,124.579,126.965,131.009,132.236,132.493,132.110,131.961,131.059
Arzl im Pitztal,2.492,2.669,2.693,2.737,2.738,2.729,2.779,2.759,2.765,2.776,...,2.989,2.983,3.030,3.039,3.042,3.088,3.134,3.157,3.164,3.140
Haiming,3.625,3.701,3.677,3.725,3.741,3.739,3.768,3.784,3.858,3.906,...,4.457,4.444,4.474,4.528,4.535,4.608,4.659,4.697,4.757,4.770
Imst,7.925,8.145,7.984,8.071,8.268,8.399,8.542,8.620,8.717,8.821,...,9.504,9.552,9.661,9.827,10.115,10.371,10.504,10.628,10.765,10.882
Imsterberg,683.000,687.000,703.000,706.000,709.000,722.000,734.000,728.000,729.000,733.000,...,743.000,761.000,757.000,774.000,763.000,769.000,777.000,801.000,801.000,794.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Weer,1.329,1.347,1.286,1.428,1.403,1.344,1.344,1.324,1.344,1.413,...,1.539,1.520,1.485,1.513,1.514,1.531,1.539,1.626,1.610,1.640
Weerberg,2.019,2.065,2.116,2.158,2.181,2.195,2.214,2.208,2.202,2.198,...,2.331,2.368,2.396,2.418,2.473,2.514,2.482,2.496,2.499,2.495
Wiesing,1.633,1.684,1.686,1.701,1.697,1.708,1.699,1.722,1.740,1.791,...,2.045,2.057,2.033,2.057,2.063,2.076,2.124,2.140,2.144,2.144
Zell am Ziller,1.934,1.928,1.957,1.974,2.000,1.946,1.927,1.885,1.884,1.857,...,1.742,1.760,1.768,1.749,1.720,1.738,1.758,1.702,1.716,1.657
Zellberg,666.000,673.000,697.000,700.000,700.000,698.000,694.000,688.000,701.000,687.000,...,631.000,645.000,655.000,649.000,651.000,653.000,648.000,645.000,665.000,680.000

1993    10.603
1994    10.617
1995    10.836
1996    11.279
1997    11.492
1998    11.884
1999    12.154
2000    12.396
2001    12.616
2002    12.917
2003    13.104
2004    13.504
2005    13.980
2006    14.283
2007    14.371
2008    14.431
2009    14.471
2010    14.520
2011    14.619
2012    14.718
2013    14.803
2014    14.986
2015    15.235
2016    15.358
2017    15.582
2018    15.747
2019    15.920
2020    16.046
2021    16.091
Name: Telfs, dtype: float64

-------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 1993 to 2021
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Telfs   29 non-null     float64
dtypes: float64(1)
memory usage: 1.5+ KB
-------------------------------------------------------------

dtype('float64')

## Version 2

In [92]:
display(population.head())

display(population.T.head())

,Bezirk,Gemnr,Gemeinde,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,I,70101.0,Innsbruck,111.305,112.174,112.759,109.150,109.763,110.454,110.997,...,119.846,122.458,124.579,126.965,131.009,132.236,132.493,132.110,131.961,131.059
2,IM,70201.0,Arzl im Pitztal,2.492,2.669,2.693,2.737,2.738,2.729,2.779,...,2.989,2.983,3.030,3.039,3.042,3.088,3.134,3.157,3.164,3.140
3,IM,70202.0,Haiming,3.625,3.701,3.677,3.725,3.741,3.739,3.768,...,4.457,4.444,4.474,4.528,4.535,4.608,4.659,4.697,4.757,4.770
4,IM,70203.0,Imst,7.925,8.145,7.984,8.071,8.268,8.399,8.542,...,9.504,9.552,9.661,9.827,10.115,10.371,10.504,10.628,10.765,10.882
5,IM,70204.0,Imsterberg,683.000,687.000,703.000,706.000,709.000,722.000,734.000,...,743.000,761.000,757.000,774.000,763.000,769.000,777.000,801.000,801.000,794.000

,1,2,3,4,5,6,7,8,9,10,...,270,271,272,273,274,275,276,277,278,279
Bezirk,I,IM,IM,IM,IM,IM,IM,IM,IM,IM,...,SZ,SZ,SZ,SZ,SZ,SZ,SZ,SZ,SZ,SZ
Gemnr,70101.0,70201.0,70202.0,70203.0,70204.0,70205.0,70206.0,70207.0,70208.0,70209.0,...,70932.0,70933.0,70934.0,70935.0,70936.0,70937.0,70938.0,70939.0,70940.0,70941.0
Gemeinde,Innsbruck,Arzl im Pitztal,Haiming,Imst,Imsterberg,Jerzens,Karres,KarrÃ¶sten,LÃ¤ngenfeld,Mieming,...,Stummerberg,Terfens,Tux,Uderns,Vomp,Weer,Weerberg,Wiesing,Zell am Ziller,Zellberg
1993,111.305,2.492,3.625,7.925,683.0,915.0,538.0,658.0,3.636,2.419,...,822.0,1.783,2.078,1.39,3.962,1.329,2.019,1.633,1.934,666.0
1994,112.174,2.669,3.701,8.145,687.0,920.0,535.0,666.0,3.74,2.487,...,825.0,1.805,2.068,1.397,3.958,1.347,2.065,1.684,1.928,673.0